version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: kapoot_dev
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050